Stage/unstabe files with double-click
JetpackDuba/Gitnuro pull request #79
Opened 2023-01-29 14:30 UTC by Philipp91

This time without introducing a delay for normal clicks.

2023-01-29 18:55 UTC, JetpackDuba commented
Hey thanks for a new PR!

The click works better but there is a bug (I'll add a comment in the code) and a few UI regressions:
- The hover does no longer work.
- The ripple has also disappeared.

2023-01-29 21:16 UTC, JetpackDuba requested changes

2023-01-29 21:32 UTC, Philipp91 commented on src/main/kotlin/com/jetpackduba/gitnuro/ui/UncommitedChanges.kt
> +            .pointerInput(Unit) { detectTapGestures(onPress = { onClick() }, onDoubleTap = { onButtonClick() }) }
So #80 won't be enough to fix this? Basically it's an outer key, but that should keep things apart properly, as it won't re-compose the same Composable instance with different StatusEntries.

(It'd be strange to hand down the `statusEntry` into the new `Modifier.clickableWithDoubleClick()` helper.)

2023-01-29 21:32 UTC, Philipp91 commented
> The hover does no longer work.

I assume you mean the "Stage" button that appears when hovering the entry. I can't reproduce this issue.

> The ripple has also disappeared.

Fixed.

2023-01-29 21:39 UTC, JetpackDuba commented
> > The hover does no longer work.
> 
> I assume you mean the "Stage" button that appears when hovering the entry. I can't reproduce this issue.

No, I mean the hover effect
![imagen](https://user-images.githubusercontent.com/16917468/215357061-c2a1a99e-7e61-443b-adcb-836e0b0c9b75.png)

It's more visible when using the light theme

![imagen](https://user-images.githubusercontent.com/16917468/215357081-f1c65011-0afd-4fb1-ba27-3d2d46b3fb26.png)

2023-01-29 22:06 UTC, Philipp91 commented
Huh, where does that hover effect even come from? And where is its color defined?

2023-01-29 22:08 UTC, JetpackDuba commented
Now that you mention it... If my memory doesn't fail, it's something done by compose desktop itself, yikes.

2023-01-29 22:18 UTC, Philipp91 commented
I could reverse-engineer the color, put it as a new entry into the Gitnuro theme and use another `backgroundIf`.

Actually I think it's not a plain color, but actually white or black (depending on dark/light theme) or a medium gray with some opacity. That's why it also works on top of the "selected" background.

2023-01-29 22:28 UTC, JetpackDuba commented
Nah, don't worry, we can just pick a new color instead. I'll look into it tomorrow.

2023-02-05 21:04 UTC, Philipp91 commented
I found that the hover color isn't the only thing that's destroyed by this approach. I've implemented another approch now, which tries to interfere with the standard `clickable()` functionalities as little as possible.

2023-04-27 17:17 UTC, JetpackDuba commented
Hey!

Sorry for the late response. The last days I've been testing the changes to see if the UX is what I was expecting. The last change was great, as the delay is no longer present and displaying the diff before the second click doesn't seem like a big deal, as the double click makes most sense when the diff is already open (click to see the diff -> double click to (un)stage the file without having to move the cursor to the button).

2023-04-27 17:17 UTC, merged